### ISSUE TITLE
Move-movies move-series deletes top folder

### ISSUE THREAD

**Issue by zilexa** [Jonybat/flexget_config#19]
The folders   downseries: downloads/series/ and downmovies: downloads/movies/ are being deleted, causing flexget to give an error on the next task. In my config, I only use 1 downloadfolder for both series and movies and I checked with WinSCP: the folder exists, but while flexget is running, the folder gets deleted and eventually these errors start popping up:

```2017-06-22 23:07 INFO     scheduler                     Starting scheduler
2017-06-22 23:15 INFO     exec          move-series     Stdout: find: `/media/usbdrive/Downloads/tempmedia/*': No such file or directory
2017-06-22 23:15 INFO     exec          move-movies     Stdout: find: `/media/usbdrive/Downloads/tempmedia/*': No such file or directory
```

This is the relevant part of my secrets.yml:
```
### path of the folder/mountpoint for all the media, without the leading slash
  root: media/usbdrive/
### media and download paths, relative to the previous path
  series: TVshows
  movies: Movies
  downmedia: Downloads/tempmedia

```

There are 2 things different from your secrets.yml.sample, the first one is because it wouldn't work otherwise:
1) I had to remove the slash at the end of TVshows, Movies and Downloads/tempmedia otherwise Flexget won't run because it thinks the folders do not exist, it gives critical errors about the folders not existing the config.yml did not pass validation. Removing / at the end solved it. 
2) I just use 1 downloadfolder for series (which I call TVshows) and movies (tempmedia). 

I have found these two topics on this issue (cleanup deleting the folder):
https://discuss.flexget.com/t/cleanup-on-move-deletes-top-level-folder/491/3
https://discuss.flexget.com/t/problem-with-sorting-and-moving-files/397

But I have trouble understanding the exact solution and applying it to your config.yml. I am wondering how you solved this issue?

**Comment by zilexa** [comment]
Wow I just noticed you have created your own delete command at the very end of your move-series script, actually deleting this folder. Quoting your move-series:

```
  move-series:
    priority: 41
    template:
      - disable-seen-retry
      - series-metainfo
    filesystem:
      path: "/{? folder.root ?}{? folder.downseries ?}"
      recursive: yes
      retrieve: files
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    move:
      to: "/{? folder.root ?}{? folder.series ?}{{tvdb_series_name|escape|replace('&#39;', '')|pathscrub}}/"
      rename: "{{tvdb_series_name|escape|replace('&#39;', '')|pathscrub}} - {{tvdb_ep_id|default(series_id)}}{% if tvdb_ep_name|default(False) %} - {{tvdb_ep_name|pathscrub}}{% endif %}{% if quality|default(False) %} - [{{quality}}]{% endif %}"
      along:
        extensions:
          - srt
          - sub
        subdirs:
          - Subs
      clean_source: 50
    list_add:
      - subtitle_list:
          list: subtitles
          path: "{{location}}"
          remove_after: 7 days
    exec:
      on_exit:
        phase: find "/{? folder.root ?}{? folder.downseries ?}"* -type d -empty -delete

```

Why would you do that? This effectively deletes the folder.downseries!
The topics I posted are about the fact that the move plugin already has a little bug, deleting the path. And to workaround, you either have to create a dummy file so that downseries is never empty or set Transmission plugin path to download to downseries/staging (1 folder deeper) while the move plugin still only looks at downseries. Not sure if that actually works. 

But your move actually executes its own hard delete of your downseries folder! Now I'm lost. How does this work for you?
