### ISSUE TITLE
Question: adding Next_Trakt_Episodes based on watched status to the config

### ISSUE THREAD

**Issue by zilexa** [Jonybat/flexget_config#21]
When I run your config as is, it will download S01, S02 etc of lots of series because I have deleted the files on my harddrive. The only way for Flexget to know with which ep to start, is to look at the Trakt watched status of each series.

The quickest way to solve this is by executing this command for every tvshow:
`flexget series begin "Major Crimes" S06E01`

However the goal is to make Flexget as smart as possible, I just found a plugin that will set the beginning of each tvshow based on Trakt watched status:
https://flexget.com/Plugins/next_trakt_episodes

I understand I have to edit the task _fill-series-list_.
This is what I have done, after some trial and error, but I couldn't get it working. Below the original unmodified task:
```
##### Fetch, format and output trakt series list to a custom entry list#
  fill-series-list:
    priority: 2
    template:
      - disable-seen-retry
      - series-metainfo
    list_clear:
      what:
        - entry_list: trakt-series
    trakt_list:
      account: "{? trakt.account ?}"
      list: "{? trakt.series ?}"
      type: shows
    accept_all: yes
    set:
      title: "{{tvdb_series_name|escape|replace('&#39;', '')}}"
    list_add:
      - entry_list: trakt-series
```
So then I decided to just create a new task that will be executed right after:
```
Set-series-first-ep:
  priority: 3
  Set-series-start-episode:
    next_trakt_episodes:
      account: "{? trakt.account ?}"
      context: watched
      list: "{? trakt.series ?}"
    accept_all: yes
    set_series_begin: yes
```

I believe this should work, but since my Flexget database is now already up to date (I couldn't wait, after messing around with the original task, and executed the command for each show) I am not sure if this will work. 
But my real question: would this interfere with or get overwritten by other tasks?
